Demographic Analysis
recodehive/Stackoverflow-Analysis pull request #307
Opened 2024-06-28 18:33 UTC by ranamanish674zu

fixes #297 
@sanjay-kv i completed issue #297 could you please review it

2024-06-29 05:03 UTC, sanjay-kv requested changes
the idea is to implement on the existing ipynb. unlike other folder repo it wont work. 
Backlog is a folder I put previous contributor similar activities/

2024-06-29 11:27 UTC, ranamanish674zu commented
@sanjay-kv sir i have implement this idea over Stack_Overflow2018 file , now can you chake once

2024-06-29 11:43 UTC, sanjay-kv commented
I will take some time on this. sorry about that.

2024-06-29 11:48 UTC, ranamanish674zu commented
> I will take some time on this. sorry about that.

@sanjay-kv okay sir no issue take your time

2024-07-03 12:10 UTC, ranamanish674zu commented
@sanjay-kv has  review completed ?

2024-08-03 01:33 UTC, closed without merging